#!/command/with-contenv bash
# shellcheck shell=bash

# FEED_ID needs to be set

if [[ -z "${FEED_ID}" ]]; then
	echo "FEED_ID is not set, exiting"
	exit 1
fi

# FREQUENCIES needs to be set

if [[ -z "${FREQUENCIES}" ]]; then
	echo "FREQUENCIES is not set, exiting"
	exit 1
fi

IFS=';'
read -ra SPLIT_FREQS <<< "${FREQUENCIES}"

# loop through SPLIT_FREQS

# We can only have 6 total frequencies

if [[ "${#SPLIT_FREQS[@]}" -gt 8 ]]; then
	echo "FREQUENCIES is too long, exiting"
	exit 1
fi

# FREQUENCIES needs to be in the range of 118.0 - 137.0.

FREQ_STRING=""
for i in "${SPLIT_FREQS[@]}"
do
:
if [[ $(echo "$i > 118.0" | bc)  -eq 0 || $(echo "$i < 137.0" | bc) -eq 0 ]]; then
	echo "FREQUENCY $i is not in the range of 118.0 - 137.0, exiting"
	exit 1
fi
FREQ_STRING+=" $i"
done

# Make sure mode is valid

if [[ "${MODE}" != @(J|j|P|p|A|a) ]]; then
	echo "MODE is not valid, exiting"
	exit 1
fi

if [[ -n "${SERVER}" && -z "${SERVER_PORT}" ]]; then
	echo "SERVER is set but SERVER_PORT is not set, exiting"
	exit 1
fi

# DEVICE_ID or SERIAL needs to be set

if [[ -z "${SERIAL}" ]]; then
	echo "SERIAL is not set, exiting"
	exit 1
fi

OUTPUT_DEVICE_ID="$(timeout 1s rtl_test -d $((RANDOM+99)) 2>&1 | grep -P -e "SN: $SERIAL" | sed -n 's/^\s*\([0-9]\+\):.*$/\1/p')"

if [[ -z "${OUTPUT_DEVICE_ID}" ]]; then
	echo "Could not find device ID for serial '$SERIAL'"
	exit 1
fi

rm -rf /etc/s6-overlay/scripts/vdlm2dec > /dev/null 2>&1
if [[ -n "${OUTPUT_DEVICE_ID}" ]]; then
	cp /etc/templates/run /etc/s6-overlay/scripts/vdlm2dec
else
	cp /etc/templates/bad /etc/s6-overlay/scripts/vdlm2dec
fi

s6-chmod 0755 /etc/s6-overlay/scripts/vdlm2dec

mkdir -p /run/acars
touch /run/acars/vdlm2.past5min.json

#sed -i "s/DEVICE_ID=\"\"/DEVICE_ID=\"$OUTPUT_DEVICE_ID\"/g" /etc/s6-overlay/scripts/vdlm2dec
sed -i "s/FREQ_STRING=\"\"/FREQ_STRING=\"$FREQ_STRING\"/g" /etc/s6-overlay/scripts/vdlm2dec

# Everything is good to go. Exit with 0

exit 0
