#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

# FEED_ID needs to be set

if [[ -z "${FEED_ID}" ]]; then
	# shellcheck disable=SC2154
	"${s6wrap[@]}" echo "FEED_ID is not set, exiting"
	exit 1
fi

# FREQUENCIES needs to be set

if [[ -z "${FREQUENCIES}" ]]; then
	"${s6wrap[@]}" echo "FREQUENCIES is not set, exiting"
	exit 1
fi

IFS=';'
read -ra SPLIT_FREQS <<< "${FREQUENCIES}"

# loop through SPLIT_FREQS

# We can only have 6 total frequencies

if [[ "${#SPLIT_FREQS[@]}" -gt 8 ]]; then
	"${s6wrap[@]}" echo "FREQUENCIES is too long, exiting"
	exit 1
fi

# FREQUENCIES needs to be in the range of 118.0 - 137.0.

FREQ_STRING=""
for i in "${SPLIT_FREQS[@]}"
do
:
if [[ $(echo "$i > 118.0" | bc)  -eq 0 || $(echo "$i < 137.0" | bc) -eq 0 ]]; then
	"${s6wrap[@]}" echo "FREQUENCY $i is not in the range of 118.0 - 137.0, exiting"
	exit 1
fi
FREQ_STRING+=" $i"
done

# Make sure mode is valid

if [[ "${MODE}" != @(J|j|P|p|A|a) ]]; then
	"${s6wrap[@]}" echo "MODE is not valid, exiting"
	exit 1
fi

# DEVICE_ID or SERIAL needs to be set

if [[ -z "${SERIAL}" ]]; then
	"${s6wrap[@]}" echo "SERIAL is not set, exiting"
	exit 1
fi

mkdir -p /run/acars
touch /run/acars/vdlm2.past5min.json

#sed -i "s/DEVICE_ID=\"\"/DEVICE_ID=\"$OUTPUT_DEVICE_ID\"/g" /etc/s6-overlay/scripts/vdlm2dec
sed -i "s/FREQ_STRING=\"\"/FREQ_STRING=\"$FREQ_STRING\"/g" /etc/s6-overlay/scripts/vdlm2dec

# Everything is good to go. Exit with 0

exit 0
