#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

# if GDB is set, install GDB

if [ -n "$GDB" ]; then
    # shellcheck disable=SC2154
    "${s6wrap[@]}" echo "Installing GDB"
    "${s6wrap[@]}" apt-get update && apt-get install -y gdb
fi
