#!/command/with-contenv bash
#shellcheck shell=bash

SCRIPT_NAME="$(basename "$0")"
SCRIPT_NAME="${SCRIPT_NAME%.*}"

# shellcheck disable=SC2034
s6wrap=(s6wrap --quiet --timestamps --prepend="$SCRIPT_NAME" --args)

VDLM_BIN="/usr/local/bin/vdlm2dec"
# shellcheck disable=SC2001
FREQ_STRING=""

if [ -z "$GAIN" ]; then
    GAIN="400"
fi

VDLM_CMD=("-J" "-G" "-E" "-U" "-g" "$GAIN" "-i" "$FEED_ID")

if [ -n "${PPM}" ]; then
	VDLM_CMD+=("-p" "$PPM")
fi

if [ -n "${QUIET_LOGS}" ]; then
# 	VDLM_CMD+=("-l" "/dev/null")
# else
	VDLM_CMD+=("-v")
fi


if [[ "${MODE}" == @(J|j) ]]; then
	VDLM_CMD+=("-j" "127.0.0.1:5555")
elif [[ "${MODE}" == @(P|p) ]]; then
	VDLM_CMD+=("-n" "127.0.0.1:5555")
elif [[ "${MODE}" == @(A|a) ]]; then
	VDLM_CMD+=("-N" "127.0.0.1:5555")
fi


# Specify device ID
if [ -n "${SERIAL}" ]; then
	VDLM_CMD+=("-r" "$SERIAL")
fi

if [[ -n "$VDLM2DEC_COMMAND_EXTRA" ]]; then
	VDLM_CMD+=("$VDLM2DEC_COMMAND_EXTRA")
fi

# shellcheck disable=SC2206
VDLM_CMD+=($FREQ_STRING)

# if GDB is set, set GDB_COMMAND

if [ -n "$GDB" ]; then
	echo "GDB is set. vdlm2dec will not run automatically. Please run the following command to start vdlm2dec:"
	echo "gdb -batch -ex 'set confirm off' -ex 'handle SIGTERM nostop print pass' -ex 'handle SIGINT nostop print pass' -ex run -ex 'bt full' --args $VDLM_BIN ${VDLM_CMD[*]}"
	sleep 86400
	exit 0
fi

set -eo pipefail

"${s6wrap[@]}" echo "Starting: '$VDLM_BIN" "${VDLM_CMD[*]}'"

if [[ ${QUIET_LOGS,,} =~ true ]]; then
	# shellcheck disable=SC2016
	"${s6wrap[@]}" "$VDLM_BIN" "${VDLM_CMD[@]}" 2>&1 | \
	stdbuf -oL sed --unbuffered '/^$/d' | \
	stdbuf -oL awk '! /^dumpvdl2/' | \
	stdbuf -oL awk '! /^Sampling rate set/' | \
	stdbuf -oL awk '! /^Found \[0-9]+ device(s):/' | \
	stdbuf -oL awk '! /^  [0-9]+/' | \
	stdbuf -oL awk '! /^Using device [0-9]+/' | \
	stdbuf -oL awk '! /^Found /' | \
	stdbuf -oL awk '! /^Exact sample rate /' | \
	stdbuf -oL awk '! /^Setting sample rate/' | \
	stdbuf -oL awk '! /PLL not locked!$/' | \
	stdbuf -oL awk '! /^Center frequency set/' | \
	stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
	stdbuf -oL awk '! /^Tuner gain: /' | \
	stdbuf -oL awk '! /^Set center freq. /' | \
	stdbuf -oL awk '! /^Decoding [0-9]+ channels/' | \
	stdbuf -oL awk '! /^Allocating [0-9]+ zero-copy buffers/' | \
	stdbuf -oL awk '{print $0}'
else
	# shellcheck disable=SC2016
	"${s6wrap[@]}" "$VDLM_BIN" "${VDLM_CMD[@]}"
fi

sleep 5
