#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Require that vdlm_server is running
if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15555\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
  sleep 1
  if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    echo "[vdlm2dec] vdlm_server not running, exiting"
  fi
  exit
fi

VDLM_BIN="/usr/local/bin/vdlm2dec"
# shellcheck disable=SC2001
FREQ_STRING=""

mapfile -t RTL_TEST_OUTPUT < <(timeout 1s rtl_test -d 0 2>&1 | grep -P '^\s+\d+:\s.*?,.*?,\s+SN:\s+.*?$' | IFS=$'\n' sed -n 's/^\s*\([^:]*\):[^,]*,[^,]*,\s*SN:\s*\(.*\)$/\1,\2/; s/\s*$//p' || true)
for RTL_TEST_OUTPUT_LINE in "${RTL_TEST_OUTPUT[@]}"; do
        if [[ "${RTL_TEST_OUTPUT_LINE##*,}" == "$SERIAL" ]]; then
		DEVICE_ID="${RTL_TEST_OUTPUT_LINE%%,*}"
	fi
done

if [[ -z "${DEVICE_ID}" ]]; then
	echo "Could not find device ID for serial '$SERIAL'"
	sleep 60
	exit 1
fi

if [ -z "$GAIN" ]; then
    GAIN="400"
fi

VDLM_CMD=("-J" "-G" "-E" "-U" "-g" "$GAIN" "-i" "$FEED_ID")

if [ -n "${PPM}" ]; then
	VDLM_CMD+=("-p" "$PPM")
fi

if [ -n "${QUIET_LOGS}" ]; then
# 	VDLM_CMD+=("-l" "/dev/null")
# else
	VDLM_CMD+=("-v")
fi

# Send output JSON to acars_server
if [ -n "${SERVER}" ]; then
	if [[ "${MODE}" == @(J|j) ]]; then
		VDLM_CMD+=("-j" "127.0.0.1:5555")
	elif [[ "${MODE}" == @(P|p) ]]; then
		VDLM_CMD+=("-n" "127.0.0.1:5555")
	elif [[ "${MODE}" == @(A|a) ]]; then
		VDLM_CMD+=("-N" "127.0.0.1:5555")
	fi
fi

# Specify device ID
if [ -n "${DEVICE_ID}" ]; then
	VDLM_CMD+=("-r" "$DEVICE_ID")
fi

# shellcheck disable=SC2206
VDLM_CMD+=($FREQ_STRING)

set -eo pipefail

echo "[vdlm2dec] Starting: '$VDLM_BIN" "${VDLM_CMD[*]}'"

if [[ ${QUIET_LOGS,,} =~ true ]]; then
	# shellcheck disable=SC2016
	"$VDLM_BIN" "${VDLM_CMD[@]}" 2>&1 | \
	stdbuf -oL sed --unbuffered '/^$/d' | \
	stdbuf -oL awk '! /^dumpvdl2/' | \
	stdbuf -oL awk '! /^Sampling rate set/' | \
	stdbuf -oL awk '! /^Found \[0-9]+ device(s):/' | \
	stdbuf -oL awk '! /^  [0-9]+/' | \
	stdbuf -oL awk '! /^Using device [0-9]+/' | \
	stdbuf -oL awk '! /^Found /' | \
	stdbuf -oL awk '! /^Exact sample rate /' | \
	stdbuf -oL awk '! /^Setting sample rate/' | \
	stdbuf -oL awk '! /PLL not locked!$/' | \
	stdbuf -oL awk '! /^Center frequency set/' | \
	stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
	stdbuf -oL awk '! /^Tuner gain: /' | \
	stdbuf -oL awk '! /^Set center freq. /' | \
	stdbuf -oL awk '! /^Decoding [0-9]+ channels/' | \
	stdbuf -oL awk '! /^Allocating [0-9]+ zero-copy buffers/' | \
	stdbuf -oL awk '{print "[vdlm2dec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
	# shellcheck disable=SC2016
	"$VDLM_BIN" "${VDLM_CMD[@]}" \
	2>&1 | stdbuf -oL sed --unbuffered '/^$/d' | stdbuf -oL awk '{print "[vdlm2dec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi

sleep 5
